- name: Add Jenkins repositories
  shell: |
    wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
    rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    yum upgrade

- name: Install Jenkins
  yum:
    name: jenkins
    state: latest
